import assert from 'node:assert/strict';
import {groupRules,expandGroup} from './rule-groups.mjs';
import {normalizeRule,applicationMatches} from './rule-engine.mjs';
import {analyze} from './projects-core.mjs';
const r=(pattern,extra={})=>normalizeRule({pattern,...extra});
const rules=[r('ANIMATION'),r('LOOKDEV'),r('ANIMATION',{appFilter:'maya'}),r('ANIMATION',{from:'2026-09-23'}),r('ANIMATION',{mode:'regex'}),r('ANIMATION',{ignoreCase:false})];
const groups=groupRules(rules);assert.equal(groups.length,5);assert.equal(groups[0].entries.length,2);
const expanded=groups.flatMap(g=>expandGroup({...g,patterns:g.entries.map(r=>r.pattern).join('\n')},g.entries));assert.deepEqual(expanded,rules);
assert.throws(()=>expandGroup({mode:'regex',patterns:'valid\n['}),/Invalid regex/);
assert.equal(expandGroup({patterns:'one\ntwo\n\none'}).length,2);
assert(applicationMatches('MAYA','C:\\Program Files\\maya.exe'));assert(applicationMatches('', 'Telegram.exe'));assert(!applicationMatches('maya','mayabatch.exe'));
const start=Date.parse('2026-09-23T10:00:00Z'),event=(offset,app)=>({timestamp:new Date(start+offset*1000).toISOString(),duration:60,data:{app,title:'ANIMATION'}});
const data={windows:[event(0,'Telegram.exe'),event(60,'maya.exe')],afk:[{timestamp:new Date(start).toISOString(),duration:120,data:{status:'not-afk'}}],browsers:[]};
const p=(id,appFilter,mode='text')=>({id,name:id,color:'#65d6b4',rules:[r('ANIMATION',{appFilter,mode})]});
const result=analyze(data,[p('chat','Telegram'),p('scene','maya','regex')],start,start+120000);assert.equal(result.projects[0].total,60);assert.equal(result.projects[1].total,60);assert.equal(result.conflict,0);assert.equal(analyze(data,[p('all','')],start,start+120000).assigned,120);
console.log('PASS: lossless grouping, multiline validation, optional exact application matching, separate project totals');
